SEARCH_DIR("/usr/lib/loongarch64-linux-gnu/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/loongarch64-linux-gnu/8/")
SEARCH_DIR("/lib/loongarch64-linux-gnu/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/components/memds/lib/loongarch64-linux/gtk2/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/components/lazcontrols/lib/loongarch64-linux/gtk2/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/components/freetype/lib/loongarch64-linux/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/lazarus/packager/units/loongarch64-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/httpd22/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libpng/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/utils-pas2js/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-generics/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pxlib/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/openal/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-stl/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gnutls/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/ncurses/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/mysql/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-css/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/opengles/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pastojs/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gdbint/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gmp/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/lua/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/newt/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/cdrom/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/regexpr/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/proj4/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fpmkunit/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fppkg/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/dts/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fv/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/hash/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/svgalib/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-fpcunit/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/tcl/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-async/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/utmp/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libsee/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/postgres/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-sound/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-hash/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/httpd24/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/odbc/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-extra/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/zlib/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libusb/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/ggi/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libenet/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-report/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libxml2/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-objpas/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-net/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libcups/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fastcgi/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/webidl/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/jni/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/modplug/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/googleapi/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libcurl/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-res/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fftw/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libmicrohttpd/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-web/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fpindexer/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/symbolic/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/ptc/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/bzip2/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/openssl/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-xml/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/iconvenc/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/ldap/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/users/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/vcl-compat/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-db/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-process/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/syslog/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/bfd/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/a52/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-unicode/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/numlib/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/imagemagick/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libgd/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gitlab/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-extra/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pthreads/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/uuid/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/unzip/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-json/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gdbm/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/opengl/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/sdl/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/chm/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/dbus/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/sqlite/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libffi/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libtar/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-console/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/x11/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libnettle/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-mustache/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/dblib/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/oggvorbis/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/aspell/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libvlc/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-pdf/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/hermes/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/xforms/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/tplylib/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rsvg/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/mad/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pcap/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-passrc/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/zorba/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-registry/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-js/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/ibase/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/oracle/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libfontconfig/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/cairo/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/odata/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-sdo/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libmagic/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/libgc/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/")
SEARCH_DIR("/home/lbz/fpcupdeluxe/fpc/bin/loongarch64-linux/")
INPUT(
/usr/lib/loongarch64-linux-gnu/crti.o
/usr/lib/gcc/loongarch64-linux-gnu/8/crtbegin.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/si_c.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/project1.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/project1.or
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/system.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/lnfodwrf.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/exeinfo.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/strings.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/fpintres.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/objpas.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/cthreads.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/interfaces.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/forms.o
/home/lbz/fpcupdeluxe/lazarus/components/memds/lib/loongarch64-linux/gtk2/memdslaz.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/unit1.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/indylaz.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/linux.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/baseunix.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/unix.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/unixtype.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/initc.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/dl.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/ctypes.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/cwstring.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/dynlibs.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/unixcp.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2disableliboverlay.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2int.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/classes.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/sysutils.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/types.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/typinfo.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/rtlconsts.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/sortbase.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/errors.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/sysconst.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/unixutil.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/math.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/x11/xlib.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/x11/x.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/gdk2x.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/gdk2pixbuf.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/gtk2.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/gdk2.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/glib2.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/pango.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lmessages.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclproc.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclintf.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lcltype.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/dialogs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/controls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclstrconsts.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/graphics.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/menus.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/themes.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/buttons.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/stdctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/checklst.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/comctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/extctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclplatformdef.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/interfacebase.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wslclclasses.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wscontrols.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2winapiwindow.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2globals.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2proc.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2def.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2fontcache.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2extra.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2msgqueue.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/graphtype.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/graphmath.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazfileutils.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazutf8.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/dynhasharray.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/maps.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/integerlist.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazloggerbase.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/laztracer.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazutilities.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazstringutils.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/x11/xrender.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/cairo/cairo.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/atk.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-objpas/system.uitypes.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/fpcadds.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazclasses.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazmethodlist.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-objpas/strutils.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/gettext.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/laz_avl_tree.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazutilsstrconsts.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/fileutil.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/utf8process.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazsysutils.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpimage.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/intfgraphics.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpreadbmp.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpwritebmp.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/bmpcomn.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpreadpng.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpwritepng.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpreadtiff.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpwritetiff.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fptiffcmn.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclversion.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/icnstypes.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpimgcmn.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/pngcomn.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/zstream.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/zbase.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/gzio.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/hash/crc.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/zdeflate.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/zinflate.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/trees.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/adler.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/infblock.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/infutil.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/infcodes.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/inftrees.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/inffast.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazversion.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/contnrs.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpcanvas.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpreadpnm.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpwritepnm.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpreadjpeg.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpwritejpeg.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpreadgif.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lresources.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclrescache.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsreferences.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/clipping.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jpeglib.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdapimin.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdatasrc.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdapistd.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jmorecfg.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdeferr.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jinclude.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jerror.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jmemmgr.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdmarker.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdinput.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcomapi.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jutils.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jmemnobs.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdmaster.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdcolor.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdsample.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdpostct.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jddctmgr.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdphuff.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdhuff.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdcoefct.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdmainct.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jquant1.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jquant2.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdmerge.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdct.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jidctfst.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jidctint.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jidctflt.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jidctred.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcapistd.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcapimin.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jdatadst.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcparam.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcinit.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcmarker.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcphuff.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jchuff.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcmaster.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jccolor.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcsample.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcprepct.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcdctmgr.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jccoefct.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jcmainct.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jfdctint.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jfdctfst.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/pasjpeg/jfdctflt.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-objpas/variants.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazconfigstorage.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/dynqueue.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-objpas/varutils.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/avglvltree.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazdbglog.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/syncobjs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/tmschema.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/fgl.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/masks.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-process/process.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-process/pipes.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl/termio.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/buttonpanel.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclclasses.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/clipbrd.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lcltaskdialog.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/dialogres.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/uitypes.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/custapp.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/customtimer.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/actnlist.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/helpintfs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/imglist.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/singleinstance.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fpimgcanv.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/fppixlcanv.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/pixtools.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-image/ellipses.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsimglist.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsproc.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsfactory.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/propertystorage.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/rttiutils.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsmenus.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazlogger.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/chm/fasthtmlparser.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsforms.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/imagelistcache.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/textstrings.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/extendedstrings.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsstdctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsbuttons.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/popupnotifier.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsextctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsdialogs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wschecklst.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/toolwin.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wscomctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wstoolwin.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/gtk2/gtk2ext.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/extdlgs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclmessageglue.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2debug.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/calendar.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/calcform.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wscalendar.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsextdlgs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/messages.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lclmemmanager.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsprivate.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/uriparser.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wscontrols.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazlinkedlist.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsfactory.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsstdctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wschecklst.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2themes.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/spin.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/grids.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/pairsplitter.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsspin.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-xml/htmldefs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/maskedit.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/dynamicarray.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/laz2_xmlcfg.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lcsvutils.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/lazfilecache.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/laz2_dom.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/laz2_xmlread.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/laz2_xmlwrite.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/laz2_xmlutils.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsgrids.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wspairsplitter.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsbuttons.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wscalendar.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wscomctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsdialogs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsextctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsextdlgs.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsforms.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsgrids.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsimglist.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsmenus.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wsspin.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2wspairsplitter.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/unitywsctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2cellrenderer.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/gtk2/gtk2listviewtreemodel.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-db/memds.o
/home/lbz/fpcupdeluxe/lazarus/components/memds/lib/loongarch64-linux/gtk2/frmselectdataset.o
/home/lbz/fpcupdeluxe/lazarus/packager/units/loongarch64-linux/lazaruspackageintf.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-db/db.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-objpas/fmtbcd.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/maskutils.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-db/dbconst.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/componenteditors.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/propedits.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/lazstringgridedit.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/checklistboxeditordlg.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/checkgroupeditordlg.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/propeditutils.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/componentreg.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/objinspstrconsts.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/idewindowintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/ideoptionsintf.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/lazideintf.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lazhelphtml.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/baseideintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/compoptsintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/projectintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/ideexterntoolintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/packageintf.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/ideopteditorintf.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/srceditorintf.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/lazhelpintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/macrointf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/macrodefintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/newitemintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/projpackintf.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/buildstrconsts.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/packagedependencyintf.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/editorsyntaxhighlighterdef.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/idecommands.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/ideimagesintf.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/editbtn.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/valedit.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/filectrl.o
/home/lbz/fpcupdeluxe/lazarus/components/lazcontrols/lib/loongarch64-linux/gtk2/checkboxthemed.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/stringhashlist.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/frmselectprops.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/stringspropeditdlg.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/keyvalpropeditdlg.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/collectionpropeditform.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/filefilterpropeditor.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/pagespropeditdlg.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/groupededit.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/calendarpopup.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-objpas/dateutils.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/timepopup.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/shellctrls.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/wsshellctrls.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/texttools.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/formeditingintf.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/objectinspector.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/idedialogs.o
/home/lbz/fpcupdeluxe/lazarus/components/buildintf/units/loongarch64-linux/lazmsgworker.o
/home/lbz/fpcupdeluxe/lazarus/components/lazutils/lib/loongarch64-linux/compwriterpas.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/unitresources.o
/home/lbz/fpcupdeluxe/lazarus/components/lazcontrols/lib/loongarch64-linux/gtk2/treefilteredit.o
/home/lbz/fpcupdeluxe/lazarus/components/lazcontrols/lib/loongarch64-linux/gtk2/listfilteredit.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/idehelpintf.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/componenttreeview.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/oifavoriteproperties.o
/home/lbz/fpcupdeluxe/lazarus/components/ideintf/units/loongarch64-linux/gtk2/changeparentdlg.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdURI.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/DataSet.Serialize.o
/home/lbz/fpcupdeluxe/lazarus/lcl/units/loongarch64-linux/dbgrids.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcHttpCli.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcDB.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHTTP.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcInfo.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/VirtualTable.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcSystem.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-json/fpjson.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdException.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdGlobal.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/rtl-extra/sockets.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/iconvenc/iconvenc.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdResourceStrings.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdStream.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdStreamVCL.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdGlobalProtocols.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdResourceStringsProtocols.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUriUtils.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCharsets.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdBaseComponent.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIPAddress.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAssignedNumbers.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdResourceStringsCore.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdStack.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdStackConsts.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCTypes.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdStackUnix.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdStackBSDBase.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-net/netdb.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdResourceStringsUnix.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdResourceStringsUriUtils.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-json/jsonparser.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/DataSet.Serialize.Language.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/DataSet.Serialize.Config.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-json/jsonscanner.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-json/jsonreader.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/DataSet.Serialize.Export.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/DataSet.Serialize.Import.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/fcl-base/base64.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/DataSet.Serialize.Utils.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/DataSet.Serialize.Consts.o
/home/lbz/fpcupdeluxe/QFDataSet_unidac/Client_json/lib/loongarch64-linux/DataSet.Serialize.UpdatedStatus.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcTypes.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcLog.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcConn.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcPlugins.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcDataCli.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcSrcList.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcSrcTypes.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcThrPool.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcTimer.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcLink.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcConnProv.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcSynSocket.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcSocketHttpCliProv.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcSynAPI.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcSockBase.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcCrypt.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcSocketCliProv.o
/home/lbz/fpcupdeluxe/ccr/RealThinClientSDK_v952/Lib/lib/loongarch64-linux/rtcZLib.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/paszlib.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/zcompres.o
/home/lbz/fpcupdeluxe/fpc/units/loongarch64-linux/paszlib/zuncompr.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdExceptionCore.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHeaderList.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHTTPHeaderInfo.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdReplyRFC.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSSL.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdZLibCompressorBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTCPClient.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCookie.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCookieManager.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAuthentication.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAuthenticationManager.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMultipartFormData.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoderMIME.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoder3to4.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoder.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdReply.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIOHandler.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIOHandlerSocket.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIOHandlerStack.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdScheduler.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdServerIOHandler.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdYarn.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAntiFreezeBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdBuffer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdComponent.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIntercept.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCustomTransparentProxy.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSocketHandle.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSocks.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTCPConnection.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdThread.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTask.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdThreadSafe.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSchedulerOfThread.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTCPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCustomTCPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdContext.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdServerIOHandlerStack.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdServerIOHandlerSocket.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdGlobalCore.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSchedulerOfThreadDefault.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoderHeader.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdEMailAddress.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHeaderCoderBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAllHeaderCoders.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHeaderCoderPlain.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHeaderCoder2022JP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHeaderCoderIndy.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoderQuotedPrintable.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAllAuthentications.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAuthenticationNTLM.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAuthenticationDigest.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdResourceStringsOpenSSL.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSSLOpenSSLHeaders.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSSLOpenSSL.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdNTLM.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFIPS.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdStruct.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHash.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHashMessageDigest.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/MemData.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/MemDataSet.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRTypes.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CLRClasses.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRFunctions.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRTimeStamp.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRParser.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/MemUtils.o
DAConsts.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRXml.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAboutVCL.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAntiFreeze.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoreDsnRegister.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDsnCoreResourceStrings.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDsnPropEdBindingVCL.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDsnRegister.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDsnResourceStrings.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDsnSASLListEditorFormVCL.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRegister.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRegisterCore.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASL.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLCollection.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdBlockCipherIntercept.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdChargenServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdChargenUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoderBinHex4.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoderUUE.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoderXXE.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCompressorZLib.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCompressionIntercept.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdConnectThroughHttpProxy.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDateTimeStamp.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDayTime.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDayTimeServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDayTimeUDP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDayTimeUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDICT.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDICTServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDiscardServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDiscardUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDNSResolver.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDNSServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdEcho.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdEchoServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdEchoUDP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdEchoUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFinger.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFingerServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFSP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdGopher.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdGopherServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHTTPProxyServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHTTPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIPAddrMon.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIdent.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIdentServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIMAP4.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIMAP4Server.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIPWatch.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIRC.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIrcServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdLPR.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMailBox.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMappedFTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMappedPortTCP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMappedTelnet.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMappedPOP3.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMappedPortUDP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessage.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageCoderMIME.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageCoderYenc.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdNetworkCalculator.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdNNTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdNNTPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdPOP3.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdPOP3Server.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdQotd.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdQotdServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdQOTDUDP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdQOTDUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRexec.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRexecServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRSH.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRSHServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLAnonymous.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLDigest.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLExternal.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLLogin.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLOTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLPlain.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLSKey.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASLUserPass.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASL_CRAM_MD5.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASL_CRAM_SHA1.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdServerInterceptLogEvent.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdServerInterceptLogFile.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSMTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSMTPRelay.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSMTPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSNMP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSNPP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSNTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSocksServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSysLog.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSysLogMessage.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSysLogServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSystat.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSystatServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSystatUDP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSystatUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTelnet.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTelnetServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTime.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTimeServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTimeUDP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTimeUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTrivialFTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTrivialFTPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUnixTime.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUnixTimeServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUnixTimeUDP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUnixTimeUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUserAccounts.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUserPassProvider.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdVCard.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdWebDAV.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdWhois.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdWhoIsServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUDPBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUDPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCoder00E.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdZLibHeaders.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdZLibConst.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdZLib.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdStrings.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdUDPClient.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDICTCommon.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCommandHandlers.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCmdTCPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdDNSCommon.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdContainers.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTPList.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTPCommon.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdExplicitTLSClientServerBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTPListParseBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdReplyFTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTPListTypes.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHashCRC.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHashSHA.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSimpleServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdOTPCalculator.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTPBaseFileSystem.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTPListOutput.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdFTPServerContextBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdGopherConsts.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTCPStream.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCustomHTTPServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageParts.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageClient.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageCoder.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageCollection.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAttachment.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIOHandlerStream.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAttachmentFile.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdText.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageCoderBinHex4.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageCoderQuotedPrintable.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageCoderUUE.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageCoderXXE.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdAttachmentMemory.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdReplyIMAP4.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdMessageHelper.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdCmdTCPClient.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdReplyPOP3.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRemoteCMDClient.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRemoteCMDServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSASL_CRAMBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHMACSHA1.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHMAC.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdHMACMD5.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdServerInterceptLogBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdLogBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSMTPBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdReplySMTP.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdASN1Util.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTrivialFTPBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIcmpClient.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdInterceptSimLog.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdInterceptThrottler.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIPMCastClient.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIPMCastServer.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdLogDebug.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdLogEvent.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdLogFile.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdLogStream.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdSchedulerOfThreadPool.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdThreadComponent.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdTraceRoute.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRawBase.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRawClient.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdRawHeaders.o
/home/lbz/fpcupdeluxe/ccr/indy/Lib/lib/loongarch64-linux/IdIPMCastBase.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRAccess.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DALoader.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DBMonitorMessages.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DBMonitorClient.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DASQLMonitor.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DBAccess.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/VirtualDataSet.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DAScript.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DADump.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRBatchMove.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRConnectionPool.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRVio.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRVioSocket.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRVioTcp.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRVioUdp.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRVioTcpSSL.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRSecureConnection.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/MTSCall.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRBase64.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRDataBuffer.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRHttp.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRVioHttp.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DAAlerter.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRDataTypeMap.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRConnectionString.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/DASQLGenerator.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CREncryption.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRSymmetricAlgorithm.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRHashAlgorithm.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRRNG.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRDECUtil.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRCryptoTransformIntf.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRCipher.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRHash.o
/home/lbz/fpcupdeluxe/ccr/UniDAC9.3.0/Lib/Lazarus1/loongarch64-linux/CRServerEnumerator.o
)
INPUT(
-lpthread
-ldl
-lgdk-x11-2.0
-lgtk-x11-2.0
-lX11
-lgdk_pixbuf-2.0
-lgobject-2.0
-lglib-2.0
-lgthread-2.0
-lgmodule-2.0
-lpango-1.0
-lcairo
-latk-1.0
-lrt
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/loongarch64-linux-gnu/8/crtend.o
/usr/lib/loongarch64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
